<?php

namespace App\Jobs;

use App\Models\ReviewTask;
use App\Services\GitHubApiService;
use App\Services\JulesApiService;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\Log;

class PollJulesSessionJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public int $tries = 30;        // Poll up to 30 times

    public int $backoff = 120;     // 2 min between retries

    public function __construct(
        public ReviewTask $task,
    ) {}

    public function handle(JulesApiService $jules, GitHubApiService $github): void
    {
        $task = $this->task;

        if ($task->status !== ReviewTask::STATUS_FIXING || ! $task->jules_session_id) {
            Log::info('Task no longer in fixing state, skipping poll', ['task' => $task->id]);

            return;
        }

        Log::info('Polling Jules session', [
            'task' => $task->id,
            'session' => $task->jules_session_id,
        ]);

        try {
            $result = $jules->getSessionOutputs($task->jules_session_id);

            if ($result['completed']) {
                // Session completed — extract PR URL
                $session = $result['session'];
                $prUrl = $jules->extractPrUrl($session);
                $repo = $task->repository;

                // If Jules didn't auto-create a PR, create one via GitHub API
                if (! $prUrl) {
                    $prUrl = $this->createPrFromJulesSession($jules, $github, $session, $task);
                }

                Log::info('Jules session completed', [
                    'task' => $task->id,
                    'pr_url' => $prUrl,
                ]);

                $task->update([
                    'status' => ReviewTask::STATUS_FIXED,
                    'jules_fix_pr_url' => $prUrl,
                ]);

                // Post a comment on the original PR linking to the fix
                if ($prUrl) {
                    $github->createIssueComment(
                        $repo->owner,
                        $repo->repo,
                        $task->pr_number,
                        "## 🔧 Auto-Fix PR Created\n\nJules has created a fix PR: {$prUrl}\n\nThis PR addresses the critical/warning issues found during the automated review.",
                    );
                }

                return;
            }

            // Session still running — re-dispatch with delay
            Log::info('Jules session still running, will poll again', ['task' => $task->id]);
            self::dispatch($task)->delay(now()->addMinutes(2));

        } catch (\Throwable $e) {
            Log::error('Failed to poll Jules session', [
                'task' => $task->id,
                'error' => $e->getMessage(),
            ]);

            // Don't fail the task, just retry
            if ($this->attempts() >= $this->tries) {
                $task->update([
                    'status' => ReviewTask::STATUS_FAILED,
                    'error_message' => 'Jules session polling timed out: '.$e->getMessage(),
                ]);
            }

            throw $e;
        }
    }

    /**
     * Create a PR on GitHub from Jules' completed session when AUTO_CREATE_PR didn't produce one.
     */
    private function createPrFromJulesSession(
        JulesApiService $jules,
        GitHubApiService $github,
        array $session,
        ReviewTask $task,
    ): ?string {
        $repo = $task->repository;

        try {
            $branchName = $jules->extractBranchName($session);

            if (! $branchName) {
                Log::warning('Could not extract branch name from Jules session', ['task' => $task->id]);

                return null;
            }

            Log::info('Creating PR from Jules branch', [
                'task' => $task->id,
                'branch' => $branchName,
                'base' => $repo->default_branch,
            ]);

            $pr = $github->createPullRequest(
                owner: $repo->owner,
                repo: $repo->repo,
                title: "🔧 Auto-Fix: Review issues in PR #{$task->pr_number}",
                head: $branchName,
                base: $repo->default_branch,
                body: "## Auto-Fix PR\n\nThis PR was automatically created to fix issues found during the code review of PR #{$task->pr_number}.\n\n**Original PR:** {$task->pr_url}\n**Review Task:** #{$task->id}\n\n---\n*Generated by Auto Code Review*",
            );

            $prUrl = $pr['html_url'] ?? null;

            Log::info('PR created successfully from Jules session', [
                'task' => $task->id,
                'pr_url' => $prUrl,
            ]);

            return $prUrl;

        } catch (\Throwable $e) {
            Log::warning('Failed to create PR from Jules session', [
                'task' => $task->id,
                'error' => $e->getMessage(),
            ]);

            return null;
        }
    }
}
